short = "cg"
# cargo --list
exact_subs = [
  "add",
  "bench",
  "bisect-rustc",
  "build",
  "careful",
  "check",
  "clean",
  "clippy",
  "config",
  "depgraph",
  "doc",
  "fetch",
  "fix",
  "fmt",
  "generate-lockfile",
  "git-checkout",
  "help",
  "init",
  "install",
  "locate-project",
  "login",
  "logout",
  "metadata",
  "miri",
  "new",
  "owner",
  "package",
  "pkgid",
  "publish",
  "read-manifest",
  "remove",
  "report",
  "run",
  "rustc",
  "rustdoc",
  "search",
  "set-version",
  "test",
  "tree",
  "uninstall",
  "update",
  "upgrade",
  "vendor",
  "verify-project",
  "version",
  "yank",
]
extract_subs = true
extract_flags = true
flags = {}

[subs.build]
short = "b"

[subs.build.flags.--release]
short = "r"
squish = true

[subs.check]
short = "c"

[subs.doc]
short = "d"
no_args = true

[subs.doc.flags.--open]
short = "o"
squish = true

[subs.clean]
short = "cl"

[subs.install]
short = "i"

[subs.install.flags.--path]
short = "p"
squish = true

[subs.run]
short = "r"

[subs.test]
short = "t"
