short = "dk"
extra_subs = []
extract_subs = true
extract_flags = true
flags = {}

[subs.build]
short = "b"

[subs.config]
extract_subs = true

[subs.container]
extract_subs = true

[subs.context]
extract_subs = true

[subs.image]
extract_subs = true

[subs.manifest]
extract_subs = true

[subs.network]
extract_subs = true

[subs.node]
extract_subs = true

[subs.push]
short = "p"

[subs.plugin]
extract_subs = true

[subs.pull]
short = "pl"

[subs.run]
short = "r"

[subs.secret]
extract_subs = true

[subs.service]
extract_subs = true

[subs.stack]
extract_subs = true

[subs.swarm]
extract_subs = true

[subs.system]
extract_subs = true

[subs.tag]
short = "t"

[subs.trust]
extract_subs = true

[subs.volume]
extract_subs = true

