short = "gl"
extra_subs = []
extract_subs = true
extract_flags = true
flags = {}

[subs.alias] # Create, list and delete aliases
extract_subs = true

[subs.api] # Make an authenticated request to GitLab API
extract_subs = true

[subs.auth] # Manage glab's authentication state
extract_subs = true

[subs.check-update] # Check for latest glab releases
extract_subs = true

[subs.ci] # Work with GitLab CI pipelines and jobs
extract_subs = true

[subs.completion] # Generate shell completion scripts
extract_subs = true

[subs.config] # Set and get glab settings
extract_subs = true

[subs.help] # Help about any command
extract_subs = true

[subs.issue] # Work with GitLab issues
extract_subs = true

[subs.label] # Manage labels on remote
extract_subs = true

[subs.mr] # Create, view and manage merge requests
extract_subs = true

[subs.release] # Manage GitLab releases
extract_subs = true

[subs.repo] # Work with GitLab repositories and projects
extract_subs = true

[subs.ssh-key] # Manage SSH keys
extract_subs = true

[subs.user] # Interact with user
extract_subs = true

[subs.variable] # Manage GitLab Project and Group Variables
extract_subs = true
