short = "j"
exact_subs = [
  "active",
  "add",
  "all",
  "annotate",
  "append",
  "blocked",
  "blocking",
  "burndown",
  "burndown.daily",
  "burndown.monthly",
  "burndown.weekly",
  "calc",
  "calendar",
  "colors",
  "columns",
  "commands",
  "completed",
  "config",
  "context",
  "count",
  "delete",
  "denotate",
  "diagnostics",
  "done",
  "duplicate",
  "edit",
  "execute",
  "export",
  "ghistory",
  "ghistory.annual",
  "ghistory.daily",
  "ghistory.monthly",
  "ghistory.weekly",
  "help",
  "history",
  "history.annual",
  "history.daily",
  "history.monthly",
  "history.weekly",
  "ids",
  "import",
  "information",
  "list",
  "log",
  "logo",
  "long",
  "ls",
  "minimal",
  "modify",
  "newest",
  "news",
  "next",
  "oldest",
  "overdue",
  "prepend",
  "projects",
  "purge",
  "ready",
  "recurring",
  "reports",
  "rm",
  "show",
  "start",
  "stats",
  "stop",
  "summary",
  "synchronize",
  "tags",
  "task",
  "udas",
  "unblocked",
  "undo",
  "uuids",
  "version",
  "waiting",
]

[subs.add]
short = "a"

[subs.next]
short = "n"

[subs.undo]
short = "ud"
