#!/usr/bin/env nix-shell
#!nix-shell -i bash -p haskellPackages.cabal-install -p docker -p gh -p git -p glab -p mdbook -p taskwarrior
set -ex
rm -f conf/conf.gen.toml
echo "# generated by scripts/conf.sh" > conf/conf.gen.toml
# TODO: nix
# TODO: systemctl
for tool in cabal cargo docker gh git glab mdbook systemctl task tmux; do
  cargo run -qr -- -vvvv extract $tool conf/$tool.toml > conf/$tool.gen.toml || exit 1
  cat conf/$tool.gen.toml >> conf/conf.gen.toml
done
cp conf/conf.gen.toml conf/conf.toml
