name: CI
on:
  push:
    branches:
    - main
  pull_request:

permissions: {}

jobs:
  CI:
    uses: langston-barrett/gha/.github/workflows/rust-ci.yml@8453c38f50561612c0baddb16d1438950c4d7473
    with:
      os: ubuntu-latest
