name: CI
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  CI:
    uses: langston-barrett/gha/.github/workflows/rust-ci.yml@a3ebfb9810611b19315959d34761a56279364347
    with:
      os: ubuntu-latest
