name: docs

on:
  push:
    branches:
    - main

concurrency:
  # Only run one of these at a time because they update the global pages. Don't
  # cancel existing runs.
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    uses: langston-barrett/gha/.github/workflows/mdbook-pages.yml@8453c38f50561612c0baddb16d1438950c4d7473
    permissions:
      contents: read
      id-token: write
      pages: write
