name: docs

on:
  push:
    branches:
    - main

concurrency:
  # Only run one of these at a time because they update the global pages. Don't
  # cancel existing runs.
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    uses: langston-barrett/gha/.github/workflows/mdbook-pages.yml@a3ebfb9810611b19315959d34761a56279364347
    permissions:
      contents: read
      id-token: write
      pages: write
