name: release

on:
  push:
    branches:
    - release*
    tags:
    - v*

jobs:
  release:
    uses: langston-barrett/gha/.github/workflows/rust-release.yml@8453c38f50561612c0baddb16d1438950c4d7473
    permissions:
      contents: write
    secrets:
      crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
    with:
      bin: zbr
      package: zbr
